# Generated by Django 3.2 on 2022-12-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futures_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to=None)),
                ('seller_name', models.CharField(default='홍길동', max_length=250)),
                ('item', models.CharField(default='None', max_length=250)),
                ('region', models.CharField(default='None', max_length=250)),
                ('sub_region', models.CharField(default='None', max_length=250)),
                ('quality', models.CharField(default='None', max_length=250)),
                ('area', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
