# Generated by Django 3.2 on 2023-01-01 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_futures_article_g_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futures_article',
            name='g_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
