# Generated by Django 3.2 on 2022-12-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potato',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField(default=0)),
                ('estimated_value_low', models.IntegerField(default=0)),
                ('estimated_value_high', models.IntegerField(default=0)),
            ],
        ),
    ]
