# Generated by Django 3.2 on 2022-12-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potato',
            name='estimated_value_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='potato',
            name='estimated_value_low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='potato',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
