# Generated by Django 3.2 on 2022-12-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20221219_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Potato',
            new_name='Carrot',
        ),
    ]
