# Generated by Django 3.2 on 2022-12-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_daegu_daejun_pusan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seoul',
        ),
    ]
