# Generated by Django 3.2 on 2022-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='item',
            field=models.TextField(default=''),
        ),
    ]
