# Generated by Django 3.2 on 2022-12-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodel', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
