# Generated by Django 3.2 on 2022-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221216_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.TextField(default='None'),
        ),
    ]
