# Generated by Django 3.2 on 2022-12-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='None', max_length=250)),
                ('seller_name', models.CharField(default='None', max_length=250)),
                ('buyer_birth', models.DateField(default='1900-01-01')),
                ('seller_birth', models.DateField(default='1900-01-01')),
                ('buyer_email', models.EmailField(default='anonymous@world.org', max_length=250)),
                ('seller_email', models.EmailField(default='anonymous@world.org', max_length=250)),
                ('buyer_address', models.TextField(default='None')),
                ('seller_address', models.TextField(default='None')),
                ('buyer_phone', models.CharField(default='None', max_length=11)),
                ('seller_phone', models.CharField(default='None', max_length=11)),
                ('farm_address', models.TextField(default='None')),
                ('item', models.TextField(default='None')),
                ('farm_area', models.IntegerField(default=0)),
                ('payment_date', models.DateField(default='2023-01-01')),
                ('payment', models.IntegerField(default=0)),
                ('advance_date', models.DateField(default='2023-01-01')),
                ('advance', models.IntegerField(default=0)),
                ('interpay_date', models.DateField(default='2023-01-01')),
                ('interpay', models.IntegerField(default=0)),
                ('balance_date', models.DateField(default='2023-01-01')),
                ('balance', models.IntegerField(default=0)),
                ('goods_date', models.DateField(default='2023-01-01')),
                ('special_contrat', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='anonymous@world.org', max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
