# Generated by Django 3.2 on 2022-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='anonymous@world.org', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='None', max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
