# Generated by Django 3.2 on 2022-12-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20221230_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='special_contrat',
            new_name='special_contract',
        ),
    ]
