# Generated by Django 3.2 on 2022-12-30 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_special_contrat_contract_special_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
