# Generated by Django 3.2 on 2023-01-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_contract_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
