# Generated by Django 3.2 on 2023-01-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_futures_article_profile'),
        ('account', '0011_auto_20230102_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='post',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='business.futures_article'),
        ),
    ]
