# Generated by Django 3.2 on 2023-01-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_contract_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='post',
        ),
    ]
