# Generated by Django 3.2 on 2023-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='account_profile_image/deal2.png', upload_to='account_profile_image'),
        ),
    ]
