# Generated by Django 3.2 on 2023-01-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='farm_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
