# Generated by Django 3.2 on 2022-12-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221209_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='written_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='written_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
