# Generated by Django 3.2 on 2022-12-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_notice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='written_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
