# Generated by Django 3.2 on 2022-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_notice_written_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='written_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
