# Generated by Django 3.2 on 2022-12-31 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20221231_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='recent_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
