# Generated by Django 3.2 on 2022-12-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_question_recent_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.CharField(default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='recent_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
