# Generated by Django 3.2 on 2023-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20221231_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writer_email',
            field=models.EmailField(default='anaonymous@gmail.org', max_length=250),
        ),
    ]
